### ISSUE TITLE
Keeps appending to same line and doesn't append a new line

### ISSUE THREAD

**Issue by mcmahonjohn** [rogerc/file-stream-rotator#25]
The following code gives me a log file that has one line constantly appended to and no new lines.

I believe this is due to file-stream-rotator as it provides the stream where the file is written to, correct?

```javascript
var FileStreamRotator = require('file-stream-rotator');
var httpLogger = require('morgan');
var logDirectory = path.join(__dirname, 'logs');
var path = require('path');

// Creates a rotating write stream
var accessLogStream = FileStreamRotator.getStream({
  date_format: 'YYYY-MM-DD',
  filename: path.join(logDirectory, '%DATE%_serverJs.log'),
  frequency: 'daily',
  verbose: true
});

app.use(httpLogger('combined', {stream: accessLogStream}));
```

**Comment by rogerc** [comment]
Hi John,

Not sure what you mean that has one line appended to it and no new lines. ``file-stream-rotator`` will write to the file it currently has open whatever is written to the stream that is returned when you initialise it.

I've used your code above with a sample express app to confirm its working OK and it has the expected output. 

```
var FileStreamRotator = require('file-stream-rotator');
var httpLogger = require('morgan');
var path = require('path');
var logDirectory = path.join(__dirname, 'logs');

// Creates a rotating write stream
var accessLogStream = FileStreamRotator.getStream({
    date_format: 'YYYY-MM-DD',
    filename: path.join(logDirectory, '%DATE%_serverJs.log'),
    frequency: 'daily',
    verbose: true
});

var express = require('express')
var app = express()
app.use(httpLogger('combined', {stream: accessLogStream}));

app.get('/', function (req, res) {
    res.send('Hello World!')
})

app.get('/hi', function (req, res) {
    res.send('Hi!')
})

app.listen(3000, function () {
    console.log('Example app listening on port 3000!')
})
```

The output I saw on the file created is below. I added a second endpoint so that you can see multiple paths rather than just hitting the same one.

``::1 - - [10/Jan/2017:19:46:03 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"``
``::1 - - [10/Jan/2017:19:46:16 +0000] "GET /hi?tz=121212 HTTP/1.1" 200 3 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"``

**Comment by mcmahonjohn** [comment]
Ah, found the issue. The text editor I was using (Notepad, shoulda known) wasn't reading the log file correctly.

Sublime Test 3 reads it fine and each output is on it's own line.

Closing this.
