### ISSUE TITLE
maxsize  size parameter issue

### ISSUE THREAD

**Issue by ashish3741** [rogerc/file-stream-rotator#56]
we are using PM2 , morgan  with file stream-rotator in production environment.we have given maxsize 50m. but it is rotating when size is 300mb. we have set the size parameter as 50m.
file-stream-rotator is having issue with PM2?

**Comment by rogerc** [comment]
@ashish3741 Most likely the issue is linked to running multiple threads/processes that are writing to the  same log file as the file size is calculated once when starting and then counted every time it writes to it but stored in each instance of the stream rotator.

if using multiple threads/processes, either route all logging to a main process or set different names using the process id for each log file.

**Comment by henrycjchen** [comment]
can we check the file size in every period of time
example code:
```js
{
  private curSize = 0;
  private lastCheckSizeTime = 0; // the latest check size time
  private checkSizeInterval = 1 * 60 * 1000; // the period of check size, here i set 1 min
  private checkSize(maxSize: number) {
    const now = Date.now();
    if (now - this.lastCheckSizeTime > this.checkSizeInterval) {
      // make sure every process check file size at the same time
      this.lastCheckSizeTime = now - (now % this.checkSizeInterval);
      const tmpFileName = this.logFile;
      fs.stat(tmpFileName, (err, stat) => {
        // make sure we check the same file
        if (!err && tmpFileName === this.logFile) {
          this.curSize = stat.size;
        }
      });
    }
    return this.curSize > maxSize;
  }
}
```

**Comment by rogerc** [comment]
as mentioned, the best fix is to route all logging through the parent process. IF you need per process logging, you can still achieve this by setting its own config per process as mentioned.
