### ISSUE TITLE
Bug: Filename RegEx causing issues with unescaped characters paths

### ISSUE THREAD

**Issue by partynikko** [rogerc/file-stream-rotator#69]
There are scenarios where the `FileStreamRotator` will crash due to the following line:
https://github.com/rogerc/file-stream-rotator/blob/d48e1ec847bd27bc7896462d0e56ba19f07c581e/FileStreamRotator.js#L483

Since the filename comparison uses a dynamic RegEx there are scenarios where the `.match` will crash due to unescaped characters in the path.

For example consider a path where the `(` characters exists which is an opening of a capture group. If no closing exists, the script will crash with an syntax error regarding not closing a capture group.
```javascript
const lastEntry = "some/path";
const tlog = "some/other/path(";

lastEntry.match(tlog); // Uncaught SyntaxError: Invalid regular expression: /some/other/path(/: Unterminated group
```

Is there a reason why this has to use `.match`? Wouldn't it suffice with something like:
```javascript
lastEntry.includes(tlog);

// or even

lastEntry === tlog;
```

Let me know what you think and I'll create a PR for it :)

Thanks
BR

**Comment by yakirzana** [comment]
+1
Any update?

**Comment by yakirzana** [comment]
In addition, it is not working correctly if the file name contains a directory.

```
const path = require('path');

const directory = "dir";
const name = "file.ext";
const nameWithNumber = "file.ext.2";

const fullPath = path.join(directory, name);
const FullNameWithNumber =path.join(directory, nameWithNumber);

console.log(FullNameWithNumber.match(fullPath)) /// null
console.log(nameWithNumber.match(name)) /// value
```

**Comment by rogerc** [comment]
reason to use match is because the file might contain, a extension and iteration number if using size as a rotation condition and only should match the beginning of the filename. if it matches then looks for the iteration number in that filename to set the iteration to use in the next file.

Plan to rewrite the module for latest JS in the coming months and I'll escape the filename when doing the matching  but since this has not been raised as an issue by others, I'll leave it as is for now.

Thanks for raising issue.
