### ISSUE TITLE
Can I submit a PR to replace moment with a more lightweight alternative?

### ISSUE THREAD

**Issue by sumeet-bansal** [rogerc/file-stream-rotator#76]
Hi @rogerc @mattberther,

I'm trying to clean up some of my dependencies for a project and noticed this repo uses moment. Can I submit a PR to replace that dependency with a more lightweight alternative like [dayjs](https://github.com/iamkun/dayjs)? I just replaced moment with dayjs in my own project and liked it because it's much smaller but has a similar API, although I'm sure there're plenty of other similar libraries that could be used.

Thanks!

**Comment by Hazmi35** [comment]
Where does the moment is used here in the first place?

**Comment by Hazmi35** [comment]
We could also use native Intl.DateTimeFormat instead of installing date libraries

**Comment by kirillku** [comment]
I'm also having the same thing. Removing `moment` from the dependencies and this is the only dependency that still uses it.

Here is [a comparison between different date libraries](https://github.com/you-dont-need/You-Dont-Need-Momentjs). Would be nice to pick something small instead of `moment`. I would pick [`date-fns/format`](https://date-fns.org/v2.16.1/docs/format) as it quite small in size and uses [unicode rules](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md), but I will be also opinionated.

@Hazmi35 I don't think `Intl.DateTimeFormat` would be a good choice in this case as most of the time you will need some parts of ISO string.

@rogerc I am proposing another option. It will make library API a bit more verbose, but still feels better. We could remove any date libraries and make `date_format` a function (`(date: Date) => string`), then everyone could use whatever is used in the project. The default value for `date_format` could be `date => date.toISOString().slice(0, 10)` (current default behavior, `2020-12-17`).

**Comment by rogerc** [comment]
I'll look at removing all dependencies in the next major release over the coming months. Thanks for raising issue.

**Comment by oceandrama** [comment]
@rogerc Hi! Do you have any plans for this? Is this repo still maintained?

**Comment by rogerc** [comment]
Hi @oceandrama Been busy finishing a project. Will look into replacing moment in October as there is another issue raised because of a CVE in the moment version used.

**Comment by oceandrama** [comment]
@rogerc Glad to hear! Let me know if I can help

**Comment by rogerc** [comment]
Hi @oceandrama  

I've pushed v1 branch that include a rewrite using Typescript. There I've removed moment.js as a dependency so the module is no dependency free. I hope to release it in the next few days. There are some small breaking changes because of the removal of moment.js but mostly behaviours remain the same.

You can have a look at it in the link below.

 https://github.com/rogerc/file-stream-rotator/tree/v1
