### ISSUE TITLE
Active file name shoudn't contain the date

### ISSUE THREAD

**Issue by panbhatt** [rogerc/file-stream-rotator#77]
WE have a requirement where we are using winston-daily-rotate-file and internally it is using this project. However all the log files (even the current one) is being created with the DATE appended to it (that means the file name is not constant). This is creating problems for the log aggregator that takes the data from the current log file. 

we need to provide an option where we can do it. I have done some changes in this and it seems to be working ok after the changes, so just wanted to know if we can submit a PR here. once it is done here, we can pass extra options via WINSTON-DAILY-ROTATE-FILE and it will all ok.

**Comment by mattberther** [comment]
Since this is related to `winston-daily-rotate-file`, I'll answer here, although it may be better for this issue to be tracked over there.

Anyways, `winston-daily-rotate-file` has options to support exactly this scenario documented in the README.md. You're probably looking for one or both of the following options:

* createSymlink: Create a tailable symlink to the current active log file. (default: false)
* symlinkName: The name of the tailable symlink. (default: 'current.log')

**Comment by drmarkfernie** [comment]
We have encountered exactly the same issue. I have created a PR with our fix for the problem.
https://github.com/rogerc/file-stream-rotator/pull/80

**Comment by rogerc** [comment]
version 0.6.0 allows for the option to not have dates in the filename.
